### ISSUE TITLE
Using dart-epub in Flutter?

### ISSUE THREAD

**Issue by l-k22** [orthros/dart-epub#33]
Sorry if I'm posting in the wrong section I did try contacting Colin awhile back via email but heard nothing back, I've also asked on StackOverflow.
Are there any examples showing how to use this inside a flutter application? Any guidance would be greatly appreciated.

**Comment by orthros** [comment]
Good hearing from you! I'm not too active in StackOverflow unfortunately. When it comes to Flutter, I must admit it has been a while since I have worked in it. 

This library will parse and read an epub book, but will not render the results. If you wanted to write a "library" application that would display a list of books and perhaps their cover, have the ability to search their contents, and download the epub to their device, this would work great for you.

If you are looking for a Flutter Widget you can plug in and render an epub inside a UI, this is not it. I have thought about writing such a widget, but I have been tied up recently, and am not sure how desirable such a widget would be.

What's the use case you are looking at?

**Comment by l-k22** [comment]
Hi, do you happen to know of any dart/flutter pagination packages? Unfortunately, the package I found only renders plain text not HTML making internal linking seemingly impossible.

thanks

**Comment by orthros** [comment]
Unfortunately, I do not know of any. Please let me know if you found one yourself!
